"""added order_index in blog

Revision ID: 00948074cd83
Revises: ab85b7ae6832
Create Date: 2025-08-25 23:31:56.068333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00948074cd83'
down_revision = 'ab85b7ae6832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('order_index')

    # ### end Alembic commands ###
