"""order_index to index

Revision ID: 169590b4fa22
Revises: 00948074cd83
Create Date: 2025-08-28 20:18:27.584058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169590b4fa22'
down_revision = '00948074cd83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.Integer(), nullable=False))
        batch_op.drop_column('order_index')

    with op.batch_alter_table('blog_paragraphs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.Integer(), nullable=False))
        batch_op.drop_column('order_index')

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.Integer(), nullable=False))
        batch_op.drop_column('order_index')

    with op.batch_alter_table('faqs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.Integer(), nullable=False))
        batch_op.drop_column('order_index')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.Integer(), nullable=False))
        batch_op.drop_column('order_index')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('index')

    with op.batch_alter_table('faqs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('index')

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('index')

    with op.batch_alter_table('blog_paragraphs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('index')

    with op.batch_alter_table('blog_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('index')

    # ### end Alembic commands ###
