"""added maintenance

Revision ID: dc4beb406e90
Revises: 5af3f1a3e049
Create Date: 2025-09-25 19:49:55.229910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc4beb406e90'
down_revision = '5af3f1a3e049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('maintenance', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance')
    # ### end Alembic commands ###
